import hyvr
import os
import shutil
import numpy as np
import scipy.io as sio
import scipy.io as sio
import filecmp

def run_testcase(inifile, runname, refname):
    """
    Runs a test ini-file and compares it to reference output.
    
    Parameters
    ----------
    inifile : path to ini-file
    runname : name of the run directory
    refname: name of the reference directory
    """

    testcasedir = os.path.relpath(os.path.join(os.path.dirname(inifile)))

    # remove old output
    if os.path.exists(os.path.join(testcasedir, runname)):
        shutil.rmtree(os.path.join(testcasedir, runname))

    # run hyvr
    hyvr.run(inifile)

    # check output
    # ============
    outputdir = os.path.join(testcasedir, runname)
    refdir = os.path.join(testcasedir, refname)

    # check parameter file
    # --------------------
    assert filecmp.cmp(os.path.join(outputdir, runname + '_autogenerated_backup.ini'),
                       os.path.join(refdir, runname + '_autogenerated_backup.ini'))

    # check numpy output
    # ------------------
    numpy_output = np.load(os.path.join(outputdir, runname + '.npz'))
    numpy_ref_output = np.load(os.path.join(refdir, runname + '.npz'))

    for name in numpy_output.files:
        assert np.all(numpy_output[name] == numpy_ref_output[name])

    numpy_output.close()
    numpy_ref_output.close()

    print("Everything okay!")
